# Generated by Django 4.2.5 on 2023-09-17 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("author_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("author_name", models.CharField(max_length=400)),
            ],
            options={
                "db_table": "author",
                "ordering": ["author_name", "author_id"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("book_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=400)),
                ("isbn13", models.CharField(max_length=13)),
                ("num_pages", models.IntegerField()),
                ("publication_date", models.DateField()),
            ],
            options={
                "db_table": "book",
                "ordering": ["title", "book_id"],
            },
        ),
        migrations.CreateModel(
            name="BookLanguage",
            fields=[
                ("language_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("language_code", models.CharField(max_length=8)),
                ("language_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "book_language",
                "ordering": ["language_name", "language_id"],
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                ("publisher_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("publisher_name", models.CharField(max_length=400)),
            ],
            options={
                "db_table": "publisher",
                "ordering": ["publisher_name", "publisher_id"],
            },
        ),
        migrations.CreateModel(
            name="BookAuthor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="books.author")),
                ("book", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="books.book")),
            ],
            options={
                "db_table": "book_author",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(related_name="books", through="books.BookAuthor", to="books.author"),
        ),
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="books.booklanguage"),
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, related_name="books", to="books.publisher"
            ),
        ),
    ]
