# Generated by Django 4.2.5 on 2023-09-17 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("address_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("street_number", models.CharField(max_length=10)),
                ("street_name", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "address",
            },
        ),
        migrations.CreateModel(
            name="AddressStatus",
            fields=[
                ("status_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("address_status", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "address_status",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("country_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("country_name", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "country",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=350)),
            ],
            options={
                "db_table": "customer",
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                ("customer_address_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("address", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="customers.address")),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="customers.customer")),
                (
                    "status",
                    models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="customers.addressstatus"),
                ),
            ],
            options={
                "db_table": "customer_address",
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="addresses",
            field=models.ManyToManyField(
                related_name="customers", through="customers.CustomerAddress", to="customers.address"
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="country",
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="customers.country"),
        ),
    ]
